FROM ubuntu:latest

# Set the working directory to /root
WORKDIR /root

# Create an apt configuration file to fix erroneous "hash sum mismatch" errors
RUN printf "Acquire::http::Pipeline-Depth 0;\nAcquire::http::No-Cache true;\nAcquire::BrokenProxy true;" \
        >> /etc/apt/apt.conf.d/99fixbadproxy

ENV DEBIAN_FRONTEND="noninteractive"

# Update packages and install Vim
RUN apt update

# Add the necessary packages to compile Elmer/Ice
RUN apt install -y \
        build-essential \
        cmake \
        git \
        libblas-dev \
        liblapack-dev \
        libmumps-dev \
        libparmetis-dev \
	libnetcdf-dev \
	libnetcdff-dev \
        mpich \
        sudo \
        less \
        unzip \
        zip \
        vim \
        gmsh \
        lua \
        curl

# ARG to specify source directory path
ARG SOURCE_DIR

# If 'SOURCE_DIR' is provided, copy the source code to the container
# Otherwise, clone the ElmerIce source code from GitHub
RUN if [ -n "$SOURCE_DIR" ]; then \
        cp -r "$SOURCE_DIR" elmer; \
    else \
        git clone https://www.github.com/ElmerCSC/elmerfem elmer; \
    fi \
    && mkdir elmer/builddir \
    && cd elmer/builddir \
    && cmake /root/elmer \
            -DCMAKE_INSTALL_PREFIX=/usr/local/Elmer-devel \
            -DCMAKE_C_COMPILER=/usr/bin/gcc \
            -DCMAKE_Fortran_COMPILER=/usr/bin/gfortran \
            -DWITH_MPI:BOOL=TRUE -DWITH_Mumps:BOOL=TRUE \
            -DWITH_Hypre:BOOL=FALSE -DWITH_Trilinos:BOOL=FALSE \
            -DWITH_ELMERGUI:BOOL=FALSE -DWITH_ElmerIce:BOOL=TRUE \
            -DWITH_LUA:BOOL=TRUE \
            -DCMAKE_Fortran_FLAGS="-fallow-argument-mismatch" \
    && make \
    && make install

# Set the path
ENV PATH=$PATH:/usr/local/Elmer-devel/bin
ENV PATH=$PATH:/usr/local/Elmer-devel/share/elmersolver/lib
ENV LD_LIBRARY_PATH=/usr/local/Elmer-devel/share/elmersolver/lib/ElmerIceUtils.so:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/Elmer-devel/share/elmersolver/lib/ElmerIceUSF.so:$LD_LIBRARY_PATH

# Add user
ENV USER=glacier
RUN adduser --disabled-password --gecos '' ${USER} \
        && adduser ${USER} sudo \
        && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER ${USER}
ENV HOME=/home/${USER}
WORKDIR ${HOME}

